version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: short_url_db
    ports:
      - "8090:3306"
    volumes:
      - ./setup-sql:/var/lib/mysql
